- name: Add Node Yum repo        
  yum_repository:
    name: nodesource-nodejs
    description: Node.js Packages for x86_64 Linux RPM based distros
    baseurl: https://rpm.nodesource.com/pub_23.x/nodistro/nodejs/x86_64
    gpgkey: https://rpm.nodesource.com/gpgkey/ns-operations-public.key

- name: Install Node.js
  yum:
    name: nodejs

- name: Create app user          
  user:
    name: app-user

- name: Install pm2              
  npm:
    name: pm2
    version: latest
    global: true

- name: Configure pm2 to run at startup as the app user
  shell: eval "$(sudo -u app-user pm2 startup -u app-user | tail -n1)"
