name: Infrastructure Tests

on: push

jobs:
  terrascan:
    name: "Run Terrascan"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      
      - name: Run Terrascan
        uses: tenable/terrascan-action@main
        with:
          iac_type: 'terraform'
          iac_dir: 'ch5/tofu/live/lambda-sample'
          verbose: true
          non_recursive: true
          config_path: 'ch5/tofu/live/lambda-sample/terrascan.toml'

  opentofu_test:
    name: "Run OpenTofu tests"
    runs-on: ubuntu-latest
    permissions:                                                                       
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v3                                 
        with:
          # TODO: fill in your IAM role ARN!
          role-to-assume: arn:aws:iam::111111111111:role/lambda-sample-tests           
          role-session-name: lambda-tests-${{ github.run_number }}-${{ github.actor }} 
          aws-region: us-east-2

      - uses: opentofu/setup-opentofu@v1                                               

      - name: Tofu Test
        env:
          TF_VAR_name: lambda-sample-${{ github.run_id }}-${{ github.run_attempt }}    
        working-directory: ch5/tofu/live/lambda-sample
        run: |                                                                         
          tofu init -backend=false -input=false
          tofu test -verbose
